version: '3.4'

services:
  leaderboardwebapi:
    image: alexthissen/leaderboard.webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:1337
      - KeyVaultName=https://retrogaming2019keyvault.vault.azure.net/
      - KeyVaultClientSecret=
      - KeyVaultClientID=
    ports:
      - "2000:1337"
    networks:
      - backend
      - frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  gamingwebapp:
    image: alexthissen/gamingwebapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LeaderboardWebApiBaseUrl=http://leaderboardwebapi:1337
    ports:
      - "80:80"
    depends_on:
      - "leaderboardwebapi"
    networks:
      - frontend
    deploy:
      replicas: 2

networks:
  frontend:
    driver: overlay
  backend:
    driver: overlay